version: "3.8"
services:
  team:
    hostname: "test"
    #restart: always
    build:
      dockerfile: Dockerfile
    command: python app.py
    ports:
      - "5000:5000"
    expose:
      - "5000"
